import Head from 'next/head'
import Link from 'next/link';
import { sanityClient, urlFor } from '../lib/sanity';


const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({recipes}) {

  
  return (
    <div>

      <Head>
        <title>The Kitchen 🍳</title>
        <meta name="description" content="Generated by next" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to The Kitchen 🍳</h1>

      <ul className="recipes-list">
        {recipes?.length > 0  && recipes.map((recipe) => (
        <li key={recipe._id} className="recipes-card">
          <Link href="/">
            <a>
              <img src={urlFor(recipe.mainImage).url()} alt="recipe" />
              <span className="recipes-text">{recipe.name} </span>
            </a>
          </Link>
        </li>
        ))}
      </ul>
    </div>
  )
}

export const getStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery)

  return { props: { recipes}};e
}