import Head from 'next/head'
import Link from 'next/link';
import { sanityClient, urlFor } from '../lib/sanity';


const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({recipes}) {

  
  return (
    <div className={styles.container}>

      <Head>
        <title>The Kitchen 🍳</title>
        <meta name="description" content="Generated by next" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to The Kitchen 🍳</h1>
    
    </div>
  )
}

export const getStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery)
rd
  return { props: { recipes}};e
}